### PR TITLE
Wip/create account hover box

### PR DESCRIPTION
**Pull request by JayOfferdahl**
Added hover box on user image to nav bar. Changed some wording around, so when a user isn't logged in, the navigation bar will only say "sign in" instead of "sign in/register".

Also removed support for small viewports (less than 768 pixles, which is the boundary for extra small devices according to bootstrap).

### CODE REVIEW

**Comment by bendavidsonku** [comment]
If you want to go ahead and add the footer to the base page like you were talking about earlier today that'd be something good to add to this pull request I think. I'm going to try to get the rest of "django-redux" done and on a pull request by tonight so we can move on to the application itself as well as creating an account settings page.

**Comment by JayOfferdahl** [comment]
Yep I'll add the footer adjustment as well.

**Comment by JayOfferdahl** [comment]
Ok, I made those changes if you want to confirm. Also, removed "invalid.html" because it was unused. Did I miss anything?

**Comment by JayOfferdahl** [comment]
Added a base favicon image to the site, this can always be changed later, but I wanted to at least get something out there.

**Comment by bendavidsonku** [comment]
I think you got all of those changes. Also invalid.html is removed in the branch I'm working on as well as every single other auth template because django-registration-redux replaces them. I updated the Kanbachi board. I think you're good to merge into master with this.

**Pull request merged**
